---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(ggraph)
library(igraph)
library(tidyverse)
```


```{r}
taskInfo <- openxlsx::read.xlsx("Generate_essentialRxns_manual/essentialRxn_notebook2022.xlsx", sheet="TaskInfo")
count.system <- table(taskInfo$System) %>% data.table() %>% setNames(c("System", "count"))
```


```{r}
# Compute the position of labels
count.system <- count.system %>% 
  arrange(desc(System)) %>%
  mutate(prop=count/sum(count.system$count)*100) %>%
  mutate(ypos=cumsum(prop)- 0.5*prop) %>%
  mutate(percent=scales::percent(count/21))

pie.system <- ggplot(count.system, aes(x="", y=count, fill=System)) +
  geom_bar(stat="identity", width=1) +
  #geom_text(aes(y=ypos, label= percent, size=4)) +
  coord_polar("y", start=0) +
  theme_void() +
  scale_fill_brewer(palette="Set2")

ggsave("Figures/secCellfie_pieChart.svg", pie.system, width = 8, height = 6)
  
```


CellFie hierarchy
```{r}
# add root node: Secretory Pathway
taskInfo$Pathway <- rep("Secretory Pathway", nrow(taskInfo))

# edge list
edges_level1_2 <- taskInfo %>% select(
  Pathway, System) %>% unique %>% rename(
  from=Pathway, to=System)

edges_level12_3 <- taskInfo %>% select(
  System, Subsystem) %>% unique %>% rename(
  from=System, to=Subsystem)
 
edges_level3_4 <- taskInfo %>% select(
  Subsystem, Task) %>% unique %>% rename(
  from=Subsystem, to=Task)

# generate graph
edge_list=rbind(edges_level1_2, edges_level12_3, edges_level3_4)
mygraph <- graph_from_data_frame( edge_list )
```

Explore different sytles
```{r}
# With igraph:
plot(mygraph, vertex.label=V(mygraph)$name, edge.arrow.size=0, vertex.size=2)

# With ggraph:
ggraph(mygraph, layout = 'dendrogram') +
  geom_edge_diagonal() +
  geom_node_text(aes( label=name)) +
  theme_void()

ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_edge_diagonal() + 
  geom_node_text(aes(label = name))

ggraph(mygraph, layout='dendrogram') + 
  geom_edge_diagonal() + 
  geom_node_text(aes(label = name, filter=leaf, angle=90)) +
  expand_limits(x = c(-1.3, 1.3), y = c(-1.3, 1.3))

ggraph(mygraph, layout='dendrogram') + 
  geom_edge_elbow2() + 
  geom_node_text(aes(label = name))

ggraph(mygraph, 'circlepack') + 
  geom_node_circle(aes(fill = depth), size = 0.25, n = 50) + 
  coord_fixed() +geom_node_text(aes(label = name))

set.seed(1)
ggraph(mygraph, 'circlepack') + 
  geom_edge_link() + 
  geom_node_point(aes(colour = depth)) +
  coord_fixed()

ggraph(mygraph, 'treemap') + 
  geom_node_tile(aes(fill = depth), size = 0.25) + 
  geom_node_text(aes(label = name)) + 
  scale_fill_viridis()

ggraph(mygraph, 'partition', circular=TRUE) + 
  geom_node_arc_bar(aes(fill=depth), size=0.25) + 
  geom_node_text(aes(label = name), size=2.7) + 
  scale_fill_viridis()


```

